CREATE TABLE `articles` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `Title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Slug` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Summary` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ImageUrl` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CategoryId` int NOT NULL DEFAULT '1',
  `AuthorId` int NOT NULL,
  `ModeratedBy` int DEFAULT NULL,
  `ModeratedAt` datetime DEFAULT NULL,
  `CreatedAt` datetime DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Status` int DEFAULT '1',
  `IsFeatured` tinyint(1) DEFAULT '0',
  `ViewCount` int DEFAULT '0',
  `RejectReason` text COLLATE utf8mb4_unicode_ci,
  `DeletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `Slug` (`Slug`),
  KEY `idx_status_date` (`Status`,`CreatedAt`),
  KEY `FK_Articles_Categories` (`CategoryId`),
  KEY `FK_Articles_Author` (`AuthorId`),
  KEY `FK_Articles_Moderator` (`ModeratedBy`),
  CONSTRAINT `fk_article_user` FOREIGN KEY (`AuthorId`) REFERENCES `users` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_Articles_Author` FOREIGN KEY (`AuthorId`) REFERENCES `users` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `FK_Articles_Categories` FOREIGN KEY (`CategoryId`) REFERENCES `categories` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `FK_Articles_Moderator` FOREIGN KEY (`ModeratedBy`) REFERENCES `users` (`Id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci